FROM python:slim-trixie

# Create non-root user and set as default
ARG USERNAME=chicken-nugget
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

USER $USERNAME

# Make all python tools installed by pip accessible
ENV PATH=$PATH:/home/$USERNAME/.local/bin

RUN pip install --no-cache-dir --upgrade pip

COPY ts-dia/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ts-dia/requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt
